import { Exercise } from "./types";

// NOTE: This seed data is deprecated and uses the old schema.
// Use the metadata management system in /admin/impostazioni instead.
// Keeping this file for reference but commenting out the data.

export const seedExercises: Exercise[] = [];

/* OLD SEED DATA - DEPRECATED
export const seedExercisesOld: Exercise[] = [
  {
    id: "ex_1",
    name: "Panca Piana Bilanciere",
    muscleGroup: "Petto",
    equipment: "gym",
    category: "Spinta Orizzontale",
    defaultRestSeconds: 180,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_2",
    name: "Squat",
    muscleGroup: "Gambe",
    equipment: "gym",
    category: "Accosciata",
    defaultRestSeconds: 240,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_3",
    name: "Stacco da Terra",
    muscleGroup: "Schiena",
    equipment: "gym",
    category: "Cerniera Anca",
    defaultRestSeconds: 240,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_4",
    name: "Military Press",
    muscleGroup: "Spalle",
    equipment: "gym",
    category: "Spinta Verticale",
    defaultRestSeconds: 120,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_5",
    name: "Trazioni",
    muscleGroup: "Schiena",
    equipment: "both",
    category: "Tirata Verticale",
    defaultRestSeconds: 180,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_6",
    name: "Rematore Bilanciere",
    muscleGroup: "Schiena",
    equipment: "gym",
    category: "Tirata Orizzontale",
    defaultRestSeconds: 120,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_7",
    name: "Affondi",
    muscleGroup: "Gambe",
    equipment: "both",
    category: "Unilaterale",
    defaultRestSeconds: 90,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_8",
    name: "Curl Bilanciere",
    muscleGroup: "Bicipiti",
    equipment: "gym",
    category: "Isolamento",
    defaultRestSeconds: 90,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_9",
    name: "French Press",
    muscleGroup: "Tricipiti",
    equipment: "gym",
    category: "Isolamento",
    defaultRestSeconds: 90,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_10",
    name: "Plank",
    muscleGroup: "Core",
    equipment: "bodyweight",
    category: "Stabilizzazione",
    defaultRestSeconds: 60,
    defaultTempo: "",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_11",
    name: "Leg Press",
    muscleGroup: "Gambe",
    equipment: "gym",
    category: "Accosciata",
    defaultRestSeconds: 180,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_12",
    name: "Panca Inclinata Manubri",
    muscleGroup: "Petto",
    equipment: "gym",
    category: "Spinta Inclinata",
    defaultRestSeconds: 120,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_13",
    name: "Lat Machine",
    muscleGroup: "Schiena",
    equipment: "gym",
    category: "Tirata Verticale",
    defaultRestSeconds: 90,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_14",
    name: "Alzate Laterali",
    muscleGroup: "Spalle",
    equipment: "gym",
    category: "Isolamento",
    defaultRestSeconds: 60,
    defaultTempo: "2010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ex_15",
    name: "Hip Thrust",
    muscleGroup: "Glutei",
    equipment: "gym",
    category: "Cerniera Anca",
    defaultRestSeconds: 120,
    defaultTempo: "3010",
    videoUrl: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
*/
